name: 'WordPress Plugin Readme/Assets Update'
description: 'Deploy readme and asset updates to the WordPress Plugin Repository'
author: '10up'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
