name: Release Pull Request Automation

on:
  create:
jobs:
  release-pull-request-automation:
    if: ${{ github.event.ref_type == 'branch' && contains( github.ref, 'release/' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate title
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo $BRANCH
          VERSION=${BRANCH#'release/'}
          echo ::set-output name=result::"Release: ${VERSION}"
        id: title
      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: develop
          title: ${{ steps.title.outputs.result }}
          template: .github/release-pull-request-template.md
